
import type { PhotoPack } from '../types';

export const productPack: Record<string, PhotoPack> = {
    'product-photography': {
        title: 'Fotografía de Producto',
        description: 'Crea fotos de marketing profesionales para tu producto.',
        images: [
            { 
                id: 58,
                key: 'white-background', 
                caption: 'Producto sobre Fondo Blanco', 
                subcategory: 'E-commerce Profesional',
                prompt: 'Take the main product in this image, professionally cut it out, and place it on a pure white background (#FFFFFF). The image should be a clean, high-resolution product shot with realistic lighting and shadows. Remove all other objects, text, and distractions from the original photo.', 
                illustration: 'product', 
                imageTypeHint: 'Sube una foto clara de tu producto.', 
                detailedDescription: "Aísla tu producto y colócalo sobre un fondo blanco puro con sombras realistas y suaves. Es el estándar de la industria para e-commerce profesional, catálogos y sitios web, garantizando una presentación limpia y enfocada. Sube una foto donde el producto se vea claramente.",
                mediaType: 'image', 
                requiresAspectRatio: true, 
            },
            { 
                id: 59,
                key: 'lifestyle-shot', 
                caption: 'Producto en Escena Lifestyle', 
                subcategory: 'Escenas Lifestyle',
                prompt: "First, identify the main product in the image. Then, place that product in a natural, realistic lifestyle setting that matches its use case. For example, if it's a water bottle, show it on a desk or in a gym bag. The lighting and context should look authentic, and the product should be placed in a physically plausible way (e.g., standing on a surface, hanging if appropriate). The final image should be a completely new scene featuring only the product from the original photo.", 
                illustration: 'product', 
                imageTypeHint: 'Sube una foto clara de tu producto.', 
                detailedDescription: "Coloca tu producto en un entorno de uso real y natural (mesa de trabajo, gimnasio, bolso, cocina). Genera contexto auténtico para aumentar el atractivo y la conexión emocional del cliente con el producto. Ideal para marketing, publicidad y redes sociales.",
                mediaType: 'image', 
                requiresAspectRatio: true, 
            },
            {
                id: 60,
                key: 'product-flat-lay',
                caption: 'Producto en Flat Lay',
                subcategory: 'Composiciones Creativas',
                prompt: "First, professionally isolate the main product or products from the source image, removing the background completely. Then, create a top-down 'flat lay' product photograph. Artfully arrange the isolated product(s) at the center of the composition. If the source image contains multiple items, arrange them in a visually pleasing stack or group. Surround the product(s) with complementary props and accessories that tell a story about their use. The background should be a clean, textured surface like wood, marble, or colored paper. The lighting must be bright and even, eliminating most shadows for a clean, graphic look.",
                illustration: 'product',
                imageTypeHint: 'Sube una foto clara de tu producto.',
                detailedDescription: "Organiza tu producto en una composición cenital 'flat lay' limpia, ordenada y artísticamente dispuesta. Sigue el estilo visual popular de Instagram y catálogos modernos. Funciona especialmente bien con sets de varios objetos, accesorios o colecciones.",
                mediaType: 'image',
                requiresAspectRatio: true,
            },
            {
                id: 61,
                key: 'product-in-use',
                caption: 'Producto en Uso (Primer Plano)',
                subcategory: 'Escenas Lifestyle',
                prompt: "First, identify the main product in the image. Then, generate a close-up, dynamic 'in-use' photograph of that product. The product should be held or used by a person (hands and arms visible, but face not the focus) in a context that demonstrates its function. For example, a hand pouring coffee from a mug, or a watch being worn on a wrist. The focus should be sharp on the product with a shallow depth of field, blurring the background. The lighting should feel natural and active.",
                illustration: 'product',
                imageTypeHint: 'Sube una foto clara de tu producto.',
                detailedDescription: "Muestra tu producto siendo utilizado por una persona (manos, muñeca, dedos). Aporta escala, contexto de uso y dinamismo a la imagen. Perfecto para relojes, tazas, herramientas, cosméticos o accesorios tecnológicos.",
                mediaType: 'image',
                requiresAspectRatio: true,
            },
            { 
                id: 62,
                key: 'studio-dark', 
                caption: 'Producto en Estudio (Fondo Oscuro)', 
                subcategory: 'E-commerce Profesional',
                prompt: "First, professionally isolate the main product from the source image, removing its original background. Then, create a professional studio photograph of the isolated product. Place it in a physically plausible way (e.g., standing on a surface, hanging if it's a hanging item) against a dark, textured background like slate or dark wood. The lighting should be dramatic (e.g., chiaroscuro) and highlight the product's features.", 
                illustration: 'product', 
                imageTypeHint: 'Sube una foto clara de tu producto.', 
                detailedDescription: "Fotografía de producto elegante sobre fondo oscuro con iluminación dramática tipo claroscuro. Resalta la exclusividad, el lujo y los detalles premium. Ideal para joyas, tecnología de alta gama, perfumes o productos de lujo.",
                mediaType: 'image', 
                requiresAspectRatio: true, 
            },
            { 
                id: 63,
                key: 'minimalist-scene', 
                caption: 'Producto en Escena Minimalista', 
                subcategory: 'Composiciones Creativas',
                prompt: "First, professionally isolate the main product from the source image, removing its original background. Then, place the isolated product in a minimalist scene. The product should be positioned naturally on or among simple geometric shapes (like blocks or pedestals). The scene should have a complementary pastel color palette, and the composition must be clean and artistic.", 
                illustration: 'product', 
                imageTypeHint: 'Sube una foto clara de tu producto.', 
                detailedDescription: "Sitúa el producto en un escenario minimalista y moderno, utilizando formas geométricas, pedestales y una paleta de colores pastel. Estética limpia, artística y contemporánea. Perfecto para cosmética, diseño y productos de estilo de vida.",
                mediaType: 'image', 
                requiresAspectRatio: true, 
            },
            { 
                id: 64,
                key: 'product-floating-surreal', 
                caption: 'Producto Flotando en Escena Surrealista', 
                subcategory: 'Composiciones Creativas',
                prompt: "First, professionally isolate the main product from the source image. Then, render a single, cohesive scene where the product and a surreal environment are fully integrated. The environment's elements (like ethereal ribbons of light or abstract shapes) must physically interact with the product—wrapping around it, passing in front of and behind it. CRITICAL: These elements must cast realistic, colored light and soft shadows ONTO the product's surfaces, and the product must cast its own shadow back onto the environment. The final image must feel like a unified, magical composition, not a product pasted onto a background. ", 
                illustration: 'product', 
                imageTypeHint: 'Sube una foto clara de tu producto.', 
                detailedDescription: "Crea una composición artística y surrealista donde el producto flota rodeado de elementos abstractos, como cintas de luz o formas etéreas. Imagen de alto impacto visual y creativo. Ideal para campañas publicitarias innovadoras y lanzamientos de producto.",
                mediaType: 'image', 
                requiresAspectRatio: true, 
            },
            { 
                id: 65,
                key: 'product-luxury-pedestal', 
                caption: 'Producto en Pedestal de Lujo', 
                subcategory: 'E-commerce Profesional',
                prompt: "First, professionally isolate the main product from the source image. Then, create a luxurious shot by placing it on an elegant pedestal (e.g., polished marble, crystal). CRITICAL for realism: The product must cast a soft, accurate shadow onto the pedestal's surface, consistent with the scene's sophisticated lighting. The lighting must wrap around both the product and pedestal, and if the pedestal is reflective, it must show subtle, accurate reflections of the product. The setting is a grand, modern showroom. The final image must look like a single, unified, high-end photograph.", 
                illustration: 'product', 
                imageTypeHint: 'Sube una foto clara de tu producto.', 
                detailedDescription: "Eleva tu producto colocándolo sobre un pedestal de mármol, cristal o piedra en un showroom de lujo. Transmite alto valor, exclusividad y sofisticación. Ideal para destacar el producto estrella de tu colección.",
                mediaType: 'image', 
                requiresAspectRatio: true, 
            },
            { 
                id: 66,
                key: 'in-nature', 
                caption: 'Producto en Entorno Natural', 
                subcategory: 'Escenas Lifestyle',
                prompt: "First, professionally isolate the main product from the source image, removing its original background. Then, place the isolated product in a beautiful nature setting, such as on a mossy rock in a forest or on sun-drenched sand at a beach. The product should be the clear focus, positioned in a physically plausible way, and integrated naturally into the environment with realistic lighting and shadows.", 
                illustration: 'product', 
                imageTypeHint: 'Sube una foto clara de tu producto.', 
                detailedDescription: "Integra el producto en un entorno natural auténtico (bosque, playa, rocas, césped). Conecta la marca con la naturaleza, frescura y sostenibilidad. Ideal para productos orgánicos, de exterior, cosmética natural o aventura.",
                mediaType: 'image', 
                requiresAspectRatio: true, 
            },
            {
                id: 67,
                key: 'showroom-text',
                caption: 'Producto en Showroom con Texto',
                subcategory: 'E-commerce Profesional',
                prompt: `First, professionally isolate the main product from the source image, removing its original background. Then, create a bright, clear photo of the isolated product, placing it in a showroom. The product should be displayed directly against a grey wall where the text "[SHOWROOM_TEXT]" is written in red at the top. The scene should be filled with bright, natural daylight streaming in from a large window. The lighting on the product must be clear and even. The product should be the main focus, similar to a smartphone's portrait mode effect. The style should be candid and realistic, with vibrant, true-to-life colors and a crisp, unretouched look.`,
                illustration: 'product',
                imageTypeHint: 'Sube una foto clara de tu producto.',
                detailedDescription: "Coloca el producto en un showroom iluminado con luz natural y tu texto personalizado en la pared. Branding integrado en la escena de forma orgánica. Escribe el nombre de tu marca, eslogan o mensaje promocional.",
                mediaType: 'image',
                requiresAspectRatio: true,
                dynamicFields: [
                    {
                        type: 'text',
                        key: '[SHOWROOM_TEXT]',
                        label: 'Texto en la Pared',
                        defaultValue: 'NEW ARRIVAL',
                        isOptional: true
                    }
                ]
            },
        ]
    }
};
